# numpy


In [1]:
import numpy as np

In [4]:
list1=[1,2,3,4]

In [16]:
n1=np.array(list1)


In [17]:
n1

array([1, 2, 3, 4])

In [18]:
type (n1)

numpy.ndarray

In [23]:
n2=np.array([[1,2,3],[4,5,6]])

In [24]:
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
type(n2)

numpy.ndarray

In [ ]:
# iniatially of numpay


In [31]:
n3=np.zeros((0,0))

In [32]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
n3=np.zeros((2,3))

In [34]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
n3=np.zeros((10,10))

In [40]:
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
#numpy as specific number

In [43]:
n3=np.full((3,3),55)

In [44]:
n3

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [ ]:
#numpy as range

In [45]:
n4=np.arange(50,100)

In [46]:
n4

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
n4=np.arange(50,100,2)

In [49]:
n4

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
#nitially as random


In [50]:
n5=np.random.randint(1,100,6)

In [51]:
n5

array([86, 88, 29, 28, 51, 59])

In [ ]:
#initially as shape 

In [64]:
n6=np.array([[1,2,30],[52,20,14]])


In [65]:
n6

array([[ 1,  2, 30],
       [52, 20, 14]])

In [71]:
n6.shape=(3,2)


In [72]:
n6

array([[ 1,  2],
       [30, 52],
       [20, 14]])

In [74]:
n6.shape=(6,1)

In [75]:
n6

array([[ 1],
       [ 2],
       [30],
       [52],
       [20],
       [14]])

In [ ]:
#two numpy join
vstack(),hstack(),column_stack()

In [76]:
n7=np.array([10,20,30])
n8=np.array([12,52,44])
np.vstack((n7,n8))

array([[10, 20, 30],
       [12, 52, 44]])

In [78]:
n1=np.array([20,21,12])
n2=np.array([40,25,35])
np.hstack((n1,n2))

array([20, 21, 12, 40, 25, 35])

In [79]:
n1=np.array([20,21,12])
n2=np.array([40,25,35])
np.column_stack((n1,n2))

array([[20, 40],
       [21, 25],
       [12, 35]])

In [81]:
n1=np.array([20,21,12,10,30,40,60,55])
n2=np.array([40,25,35,20,55,60,44])
np.intersect1d(n1,n2)

array([20, 40, 55, 60])

In [82]:
n1=np.array([20,21,12,10,30,40,60,55])
n2=np.array([40,25,35,20,55,60,44])
np.setdiff1d(n1,n2)

array([10, 12, 21, 30])

In [83]:
n1=np.array([20,21,12,10,30,40,60,55])
n2=np.array([40,25,35,20,55,60,44])
np.setdiff1d(n2,n1)

array([25, 35, 44])

In [ ]:
#addition of numpy

In [85]:
n1=np.array([20,45])
n2=np.array([40,50])
np.sum([n1,n2])

155

In [86]:
np.sum([n1,n2],axis=0)

array([60, 95])

In [87]:
np.sum([n1,n2],axis=1)

array([65, 90])

In [ ]:
#scalar 
basic addition 
basic multiplication
basic substraction
basic division

In [89]:
n1=np.array([20,21,12,10,30,40,60,55])
n1=n1+1
n1

array([21, 22, 13, 11, 31, 41, 61, 56])

In [91]:
n1=np.array([20,21,12,10,30,40,60,55])
n1=n1*2
n1

array([ 40,  42,  24,  20,  60,  80, 120, 110])

In [93]:
n1=np.array([20,21,12,10,30,40,60,55])
n1=n1-1
n1

array([19, 20, 11,  9, 29, 39, 59, 54])

In [94]:
n1=np.array([20,21,12,10,30,40,60,55])
n1=n1/2
n1

array([10. , 10.5,  6. ,  5. , 15. , 20. , 30. , 27.5])

In [ ]:
# mean ,median ,std deviation

In [95]:
n1=np.array([20,21,12,10,30,40,60,55])
np.mean(n1)

31.0

In [96]:
n1=np.array([20,21,12,10,30,40,60,55])
np.median(n1)

25.5

In [97]:
n1=np.array([20,21,12,10,30,40,60,55])
np.std(n1)

17.755280904564703

In [ ]:
#save and load

In [98]:
n1=np.array([20,21,12,10,30,40,60,55])
np.save('my_numpy',n1)

In [ ]:
n1=np.array('my_numpy.npy')
n1